# Supported robot actions (keep this aligned with the contents of unitree/robot/go2/sport/sport_api.hpp).
int32 SIT            = 1009
int32 RISESIT        = 1010
int32 HELLO          = 1016
int32 STRETCH        = 1017
int32 WALLOW         = 1021
int32 DANCE1         = 1022
int32 DANCE2         = 1023
int32 SCRAPE         = 1029
int32 FRONTFLIP      = 1030
int32 FRONTJUMP      = 1031
int32 FRONTPOUNCE    = 1032
int32 WIGGLEHIPS     = 1033
int32 HEART          = 1036
int32 DANCE3         = 1037
int32 DANCE4         = 1038
int32 HOPSPINLEFT    = 1039
int32 HOPSPINRIGHT   = 1040

# Robot action ID.
int32 id 0
