/go2/go2_control:
  ros__parameters:
    actions_sleep_time: 3000
    frame_prefix: ''
    imu_covariance:
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    init_obstacle_avoidance: true
    kill_switch_code: 16
    kill_switch_release_code: 32
    operations_stabilization_time: 1000
    operations_timeout: 1500
    pose_covariance:
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    publish_tf: true
    tf_timeout: 0.1
    twist_covariance:
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    use_utlidar: true
    velocity_control_vhorz_max: 2.0
    velocity_control_vyaw_max: 1.5
