/go2/go2_control:
  ros__parameters:
    frame_prefix: ''
    imu_covariance:
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    kill_switch_code: 16
    kill_switch_release_code: 32
    operations_stabilization_time: 1000
    operations_timeout: 1500
    pointcloud_deskewed: true
    pose_covariance:
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    - 0.01
    publish_tf: true
    velocity_control_vhorz_max: 2.0
    velocity_control_vyaw_max: 1.5
